name: Get Citation Data

on:
  push:
    branches: ['google-scholar-crawler']
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
        pip3 install -r requirements.txt
    - name: Run Py
      run: python3 main.py
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
    - name: Commit files
      run: |
        git init
        git config --local user.name "rayeren"
        git config --local user.email "rayeren613@gmail.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GHRS_GITHUB_API_TOKEN }}@github.com/${REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
      env:
        REPOSITORY: RayeRen/rayeren.github.io
        USER_EMAIL: rayeren613@gmail.com
      working-directory: ./results